AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys an RDS Subnet Group and a Multi AZ MySQL Instance 

Parameters:
  NetworkStack: 
    Description: Name of CloudFormation Stack used to create the solutions's network resources
    Type: String
  DBInstanceMasterUsername:
    Description: Admin Username for the RDS Database Instance
    Type: String
  DBInstanceSSMSecretParam:
    Description: SSM Secure Parameter for Instance's User Password
    Type: String
  DBInstanceSSMSecretParamVersion:
    Description: SSM Secure Parameter's version
    Type: String

Resources:
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet Group for MYSQL RDS instances
      DBSubnetGroupName: mysql-demo-subnet-group
      SubnetIds: 
        - Fn::ImportValue:
            !Sub "${NetworkStack}-DataTierPrivateSubnet1-ID" 
        - Fn::ImportValue:
            !Sub "${NetworkStack}-DataTierPrivateSubnet2-ID" 

  MYSQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: true
      BackupRetentionPeriod: 2
      DBInstanceClass: "db.t3.medium"
      DBInstanceIdentifier: mysql-instance
      DBName: candidates
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: mysql
      MasterUsername: !Ref DBInstanceMasterUsername
      MasterUserPassword: !Sub
        - "{{resolve:ssm-secure:${ParamName}:${Version}}}"
        - ParamName: !Ref DBInstanceSSMSecretParam
          Version: !Ref  DBInstanceSSMSecretParamVersion
      MultiAZ: true
      StorageType: gp2 
      StorageEncrypted: true
      VPCSecurityGroups: 
        -  Fn::ImportValue:
            !Sub "${NetworkStack}-DataTierSecurityGroup-ID" 
